services:
  app:
    build: .
    image: hello-node:1.0
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:4000/"]
      interval: 30s
      timeout: 3s
      retries: 3
